controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_home:
    path: /
    controller: App\Controller\AppController
    methods: GET

app_mentor_index:
    path: /mentor
    controller: App\Controller\UserController::mentorIndex
    methods: GET